In [46]:
import torch
import torch.nn as nn
import torch.utils.data as Data
import torchvision
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import numpy as np

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [18]:
train_data = pd.read_csv('./data/000651.格力电器1 - 副本.csv')
train_data.head()

,year,month,day,week,Close,High,Lower,Open,YC,zhangdiee,...,MAROC6,OSC(20),RSV(12),K(i)12,D(i)12,J(i)12,MTR,ATR(14),AR(26),BR(26)
0,1996,12,25,Wed,70.65,70.99,67.00,69.81,68.77,1.88,...,29.372370,1219.30,74.119718,61.180609,56.909284,69.723260,3.99,6.516429,186.019691,133.639706
1,1996,12,26,Thu,69.50,71.80,69.35,71.00,70.61,-1.11,...,29.650477,991.30,68.518519,63.626579,59.148382,72.582973,2.45,6.620000,190.482995,143.332535
2,1996,12,27,Fri,71.50,72.00,68.50,70.00,69.50,2.00,...,26.062947,1074.30,75.925926,67.726361,62.007709,79.163667,3.50,6.818571,184.134482,146.587895
3,1996,12,30,Mon,38.99,39.00,36.80,36.80,35.74,3.25,...,13.880329,-2132.65,5.615385,47.022702,57.012707,27.042694,34.70,8.547143,197.673742,163.432836
4,1996,12,31,Tue,38.49,40.00,37.83,39.80,38.99,-0.50,...,1.557023,-2135.45,4.668508,32.904638,48.976684,0.760546,2.17,7.845000,184.823400,162.980892

In [19]:
train_data.shape

(5199, 37)

In [21]:
features = [x for x in train_data.columns if x not in ['year', 'month', 'day', 'week']]
features

['Close',
 'High',
 'Lower',
 'Open',
 'YC',
 'zhangdiee',
 'zhangdiefu',
 'huanshoulv ',
 'Amount',
 'chengjiaojine',
 'return',
 'Label',
 'WR(5)',
 'MA(5)',
 'MA(10)',
 'MA(20)',
 'RSI(6)',
 'PSY(12)',
 'BIAS(5)',
 'BIAS(10)',
 'MTM12',
 'MTMTM6',
 'ROC(12)',
 'MAROC6',
 'OSC(20)',
 'RSV(12)',
 'K(i)12',
 'D(i)12',
 'J(i)12',
 'MTR',
 'ATR(14)',
 'AR(26)',
 'BR(26)']

In [22]:
raw_data = train_data[features]
print(raw_data.shape)
raw_data.head()

(5199, 33)

,Close,High,Lower,Open,YC,zhangdiee,zhangdiefu,huanshoulv,Amount,chengjiaojine,...,MAROC6,OSC(20),RSV(12),K(i)12,D(i)12,J(i)12,MTR,ATR(14),AR(26),BR(26)
0,70.65,70.99,67.00,69.81,68.77,1.88,2.7338,9.9676,2093200,145987072.0,...,29.372370,1219.30,74.119718,61.180609,56.909284,69.723260,3.99,6.516429,186.019691,133.639706
1,69.50,71.80,69.35,71.00,70.61,-1.11,-1.5720,3.1638,664400,46955332.0,...,29.650477,991.30,68.518519,63.626579,59.148382,72.582973,2.45,6.620000,190.482995,143.332535
2,71.50,72.00,68.50,70.00,69.50,2.00,2.8777,8.6600,1818600,128406920.0,...,26.062947,1074.30,75.925926,67.726361,62.007709,79.163667,3.50,6.818571,184.134482,146.587895
3,38.99,39.00,36.80,36.80,35.74,3.25,9.0935,19.5162,4098400,157240448.0,...,13.880329,-2132.65,5.615385,47.022702,57.012707,27.042694,34.70,8.547143,197.673742,163.432836
4,38.49,40.00,37.83,39.80,38.99,-0.50,-1.2824,5.1017,2142700,83879680.0,...,1.557023,-2135.45,4.668508,32.904638,48.976684,0.760546,2.17,7.845000,184.823400,162.980892

In [38]:
raw_data['zhangdiefu'] = raw_data['zhangdiefu'].replace('#VALUE!', 1)
raw_data['zhangdiefu'] = raw_data.zhangdiefu.astype('float')
raw_data.head()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Close,High,Lower,Open,YC,zhangdiee,zhangdiefu,huanshoulv,Amount,chengjiaojine,...,MAROC6,OSC(20),RSV(12),K(i)12,D(i)12,J(i)12,MTR,ATR(14),AR(26),BR(26)
0,70.65,70.99,67.00,69.81,68.77,1.88,2.7338,9.9676,2093200,145987072.0,...,29.372370,1219.30,74.119718,61.180609,56.909284,69.723260,3.99,6.516429,186.019691,133.639706
1,69.50,71.80,69.35,71.00,70.61,-1.11,-1.5720,3.1638,664400,46955332.0,...,29.650477,991.30,68.518519,63.626579,59.148382,72.582973,2.45,6.620000,190.482995,143.332535
2,71.50,72.00,68.50,70.00,69.50,2.00,2.8777,8.6600,1818600,128406920.0,...,26.062947,1074.30,75.925926,67.726361,62.007709,79.163667,3.50,6.818571,184.134482,146.587895
3,38.99,39.00,36.80,36.80,35.74,3.25,9.0935,19.5162,4098400,157240448.0,...,13.880329,-2132.65,5.615385,47.022702,57.012707,27.042694,34.70,8.547143,197.673742,163.432836
4,38.49,40.00,37.83,39.80,38.99,-0.50,-1.2824,5.1017,2142700,83879680.0,...,1.557023,-2135.45,4.668508,32.904638,48.976684,0.760546,2.17,7.845000,184.823400,162.980892

In [81]:
train_x = raw_data[[x for x in raw_data.columns if x != 'Label']]
train_y = raw_data['Label']

train_x.head()

,Close,High,Lower,Open,YC,zhangdiee,zhangdiefu,huanshoulv,Amount,chengjiaojine,...,MAROC6,OSC(20),RSV(12),K(i)12,D(i)12,J(i)12,MTR,ATR(14),AR(26),BR(26)
0,70.65,70.99,67.00,69.81,68.77,1.88,2.7338,9.9676,2093200,145987072.0,...,29.372370,1219.30,74.119718,61.180609,56.909284,69.723260,3.99,6.516429,186.019691,133.639706
1,69.50,71.80,69.35,71.00,70.61,-1.11,-1.5720,3.1638,664400,46955332.0,...,29.650477,991.30,68.518519,63.626579,59.148382,72.582973,2.45,6.620000,190.482995,143.332535
2,71.50,72.00,68.50,70.00,69.50,2.00,2.8777,8.6600,1818600,128406920.0,...,26.062947,1074.30,75.925926,67.726361,62.007709,79.163667,3.50,6.818571,184.134482,146.587895
3,38.99,39.00,36.80,36.80,35.74,3.25,9.0935,19.5162,4098400,157240448.0,...,13.880329,-2132.65,5.615385,47.022702,57.012707,27.042694,34.70,8.547143,197.673742,163.432836
4,38.49,40.00,37.83,39.80,38.99,-0.50,-1.2824,5.1017,2142700,83879680.0,...,1.557023,-2135.45,4.668508,32.904638,48.976684,0.760546,2.17,7.845000,184.823400,162.980892

In [82]:
# 做数据集标准化

# 初始化缩放器
scaler = MinMaxScaler()

# 拟合，计算缩放操作需要的个字段的最大和最小值
scaler.fit(train_x)
minmax_train_x = scaler.transform(train_x)
minmax_train_x[0]

array([0.98669172, 0.98429482, 0.96197411, 0.98123028, 0.97078438,
       0.84815436, 0.87470619, 0.5099437 , 0.00408837, 0.00798687,
       0.92612514, 0.0170085 , 0.93320236, 1.        , 0.94827441,
       0.71337427, 0.6       , 0.89673681, 0.78463445, 1.        ,
       0.98878418, 0.91406665, 0.91423717, 0.96670124, 0.78028616,
       0.63230672, 0.5896565 , 0.65464683, 0.11421979, 0.7598209 ,
       0.50292204, 0.09185985])

In [83]:
# 将ndarray类型数据转化为tensor类型
train_x = torch.from_numpy(minmax_train_x)
train_y = torch.from_numpy(train_y.values)

# 将DoubleTensor转化为FloatTensor
train_x = train_x.type(torch.FloatTensor)
train_y = train_y.type(torch.FloatTensor)

In [113]:
# 设置pytorch的随机种子，保证结果能够复现
torch.manual_seed(1)    # reproducible

# 设置超参数
EPOCH = 10    # 设置迭代训练的轮数
BATCH_SIZE = 260     # 设置每轮迭代训练的样本数
LR = 0.05         # learning rate

# 构建适用于pytorch的数据集
torch_dataset = Data.TensorDataset(train_x, train_y)

# 封装数据集，并对数据集分batch
train_loader = Data.DataLoader(
    dataset=torch_dataset,      # torch TensorDataset format
    batch_size=BATCH_SIZE,      # mini batch size
    shuffle=True,               # random shuffle for training
    num_workers=2,              # subprocesses for loading data
)

In [114]:
# 定义自编码器类
class AutoEncoder(nn.Module):
    # 设置网络结构（编码器+解码器）
    def __init__(self):
        super(AutoEncoder, self).__init__()

        self.encoder = nn.Sequential(
            nn.Linear(32, 20),
            nn.Tanh(),
            nn.Linear(20, 10),
            nn.Tanh(),
            nn.Linear(10, 8),
#             nn.Tanh(),
#             nn.Linear(12, 3),   # compress to 3 features which can be visualized in plt
        )
        self.decoder = nn.Sequential(
            nn.Linear(8, 10),
            nn.Tanh(),
            nn.Linear(10, 20),
            nn.Tanh(),
            nn.Linear(20, 32),
#             nn.Tanh(),
#             nn.Linear(128, 28*28),
#             nn.Sigmoid(),       # compress to a range (0, 1)
        )
    
    # 设置网络前向传播过程
    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

# 初始化自编码器
autoencoder = AutoEncoder()
print(autoencoder)

# 设置神经网络的优化函数
optimizer = torch.optim.Adam(autoencoder.parameters(), lr=LR)
# 设置神经网络的损失函数
loss_func = nn.MSELoss()

# 迭代训练
for epoch in range(EPOCH):
    # 每轮需要训练所有的batch数据块
    for step, (x, b_label) in enumerate(train_loader):
        # 将数据块转化为32列
        b_x = x.view(-1, 32)
        b_y = x.view(-1, 32)
        
        # 将一个batch的数据块输入网络中
        encoded, decoded = autoencoder(b_x)
        
        # 计算真实值与解码值的损失
        loss = loss_func(decoded, b_y)      # mean square error
        
        # 网络梯度清零
        optimizer.zero_grad()               # clear gradients for this training step
        
        # 网络反向传播
        loss.backward()                     # backpropagation, compute gradients
        
        # 更新网络参数
        optimizer.step()                    # apply gradients
        
        # 设置没10个batch输出网络的损失
        if step % 10 == 0:
            print('Epoch: ', epoch, '| train loss: %.4f' % loss.data.numpy())

AutoEncoder(
  (encoder): Sequential(
    (0): Linear(in_features=32, out_features=20, bias=True)
    (1): Tanh()
    (2): Linear(in_features=20, out_features=10, bias=True)
    (3): Tanh()
    (4): Linear(in_features=10, out_features=8, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=8, out_features=10, bias=True)
    (1): Tanh()
    (2): Linear(in_features=10, out_features=20, bias=True)
    (3): Tanh()
    (4): Linear(in_features=20, out_features=32, bias=True)
  )
)
Epoch:  0 | train loss: 0.3915
Epoch:  0 | train loss: 0.0309
Epoch:  1 | train loss: 0.0270
Epoch:  1 | train loss: 0.0197
Epoch:  2 | train loss: 0.0157
Epoch:  2 | train loss: 0.0110
Epoch:  3 | train loss: 0.0072
Epoch:  3 | train loss: 0.0062
Epoch:  4 | train loss: 0.0057
Epoch:  4 | train loss: 0.0048
Epoch:  5 | train loss: 0.0064
Epoch:  5 | train loss: 0.0053
Epoch:  6 | train loss: 0.0055
Epoch:  6 | train loss: 0.0051
Epoch:  7 | train loss: 0.0049
Epoch:  7 | train loss: 0.0051
Epoch:  8 | train loss: 0.0050
Epoch:  8 | train loss: 0.0044
Epoch:  9 | train loss: 0.0054
Epoch:  9 | train loss: 0.0050

In [116]:
# 利用训练好的自编码器对训练集train_x进行降维
encode_train_x,_ = autoencoder(train_x)
encode_train_x.size()

torch.Size([5199, 8])

In [119]:
# 将降维后的tensor转化为numpy,在转化为DataFrame，最后导出为csv文件
pd.DataFrame(encode_train_x.data.numpy()).to_csv('降维特征.csv', index=None)